version: '3.9'

services:
  web-app:
    image: nginx:latest
    volumes:
      - ./web-app/dist:/usr/share/nginx/html
    ports:
      - "8080:80"

  dotnet-api:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dege1994
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data:
    driver: local