@url = https://dg-api-w.azurewebsites.net/api/Authentication
@url-docker = http://localhost:8080/api/Authentication

POST {{url-docker}}/login
Content-Type: application/json

{
    "email":"douglbb1@gmail.com",
    "password":"123tes"
}