@url = https://dg-api-w.azurewebsites.net/api/Authentication
@url-docker = http://localhost:8080/api/Authentication
@url-dev = http://localhost:5062/api/Authentication

POST {{url-dev}}/login
Content-Type: application/json

{
    "email":"test@email.com",
    "password":"111111"
}