@url = https://dg-api-w.azurewebsites.net/api/Authentication
@url-docker = http://localhost:8080/api/Authentication
@url-dev = https://localhost:7204/api/Authentication

POST {{url-dev}}/login
Content-Type: application/json

{
    "email":"test1512@test.com",
    "password":"111111"
}