@url-dev = http://localhost:5062/api/Exchange/bybit
@token = 
###
POST {{url-dev}}/credentials
Content-Type: application/json  
Authorization: Bearer {{token}}

{
    "accountId": 1,
    "apiKey": "0",
    "apiSecret": "0",
    "webhookSecret": "first-test-webhook-secret"
}

###
POST {{url-dev}}/sync-accounts
Content-Type: application/json  
Authorization: Bearer {{token}}
