@url = http://localhost:5059/api/Crypto
@token = ''

POST {{url}}/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "crypto":"USDT",
    "currency":"Theter",
    "coinMarketCapId": 825
}

###
POST {{url}}/create-crypto
Content-Type: application/json

{
    "name":"BNB",
    "symbol":"BNB",
    "image":"bnb-logo.png",
    "coinMarketCapId": 4030
}


###
POST {{url}}/add-transaction
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount":5,
    "price":0.89,
    "purchaseDate":"2023-08-18",
    "ExchangeName":"binance",
    "transactionType":1,
    "cryptoAssetId":1
}

###
GET {{url}}/list-assets?page=1&pageSize=10&sort_order=ASC
Authorization: Bearer {{token}}
# &cryptoCurrency=btc&sortColumn=link&page=1&pageSize=3&sortOrder=asc


###
GET {{url}}/get-crypto-asset-by-id/1
Authorization: Bearer {{token}}

###
GET {{url}}/test
Authorization: Bearer {{token}}