@url = http://localhost:5059/api/Crypto
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW9AdGVzdGUuY29tIiwibmFtZWlkIjoiMSIsInVuaXF1ZV9uYW1lIjoiSm9hbyIsInJvbGUiOiJVc2VyIiwibmJmIjoxNjk5NDc2MzE2LCJleHAiOjE2OTk1NjI3MTYsImlhdCI6MTY5OTQ3NjMxNiwiaXNzIjoiaHR0cDovL215LWxvY2FsLWhvc3QuY29tIn0.UU64ohvprwT7hGNTkX4jOdsKU0nprZ5QuITotlwkGrk

POST {{url}}/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "crypto":"USDT",
    "currency":"Theter",
    "coinMarketCapId": 825
}


###
POST {{url}}/add-transaction
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount":5,
    "price":0.89,
    "purchaseDate":"2023-08-18",
    "ExchangeName":"binance",
    "transactionType":1,
    "cryptoAssetId":1
}

###
GET {{url}}/list-assets?page=1&pageSize=10&cryptoCurrency=h
Authorization: Bearer {{token}}
# &cryptoCurrency=btc&sortColumn=link&page=1&pageSize=3&sortOrder=asc


###
GET {{url}}/get-crypto-asset-by-id/1
Authorization: Bearer {{token}}