@url = http://localhost:5059/api/Crypto
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRoZW9AZ21haWwuY29tIiwibmFtZWlkIjoiMSIsInVuaXF1ZV9uYW1lIjoiVGhlbyIsInJvbGUiOiJBZG1pbiIsIm5iZiI6MTcxNzg0NjAzNCwiZXhwIjoxNzE3OTMyNDM0LCJpYXQiOjE3MTc4NDYwMzQsImlzcyI6Imh0dHA6Ly9teS1sb2NhbC1ob3N0LmNvbSJ9.NgAjU-E11El8h8FvldKTnlFGG87cp4gVWaXf_T8fJSk

POST {{url}}/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "crypto":"USDT",
    "currency":"Theter",
    "coinMarketCapId": 825
}


###
POST {{url}}/add-transaction
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "amount":5,
    "price":0.89,
    "purchaseDate":"2023-08-18",
    "ExchangeName":"binance",
    "transactionType":1,
    "cryptoAssetId":1
}

###
GET {{url}}/list-assets?page=1&pageSize=10&sort_order=ASC
Authorization: Bearer {{token}}
# &cryptoCurrency=btc&sortColumn=link&page=1&pageSize=3&sortOrder=asc


###
GET {{url}}/get-crypto-asset-by-id/1
Authorization: Bearer {{token}}

###
GET {{url}}/test
Authorization: Bearer {{token}}