@url = http://localhost:5059/api/User
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvYW9AdGVzdGUuY29tIiwibmFtZWlkIjoiMSIsInVuaXF1ZV9uYW1lIjoiR29tZXMiLCJyb2xlIjoiVXNlciIsIm5iZiI6MTcwNTc5MDU4MywiZXhwIjoxNzA1ODc2OTgzLCJpYXQiOjE3MDU3OTA1ODMsImlzcyI6Imh0dHA6Ly9teS1sb2NhbC1ob3N0LmNvbSJ9.kVmkV4vy0nttSx1vezFPvqP3i_mzZBKu2PhaxKt3tHU
PUT {{url}}/update-user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName" : "Joao",
    "lastName" : "Gomes",
    "email" : "joao@teste.com",
    "role" : 2,
    "userId" : 1,
    "creatorId" : 1
}

###
POST {{url}}/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fullName":"Davison",
    "email":"daviison@ttest.com",
    "role":2
}

###

GET {{url}}/list-users?page=1&pageSize=10
Authorization: Bearer {{token}}

###
GET {{url}}/get-user-by-id/2
Authorization: Bearer {{token}}