@url = http://localhost:5059/api/user
@token = 
PUT {{url}}/update-user
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName" : "Joao",
    "lastName" : "Gomes",
    "email" : "joao@teste.com",
    "role" : 2,
    "userId" : 1,
    "creatorId" : 1
}

###
POST {{url}}/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fullName":"Theo Giz",
    "email":"theo@gmail.com",
    "role":1
}

###

GET {{url}}/list-users?page=1&pageSize=10
Authorization: Bearer {{token}}

###
GET {{url}}/get-user-by-id/2
Authorization: Bearer {{token}}