@url = http://localhost:7071/api/cryptos

POST {{url}}/create-crypto-asset
Content-Type: application/json

{
    "crypto":"twt",
    "currency":"usd"
}


###
POST {{url}}/create-crypto-transaction
Content-Type: application/json

{
    "amount":5,
    "price":0.89,
    "purchaseDate":"2023-08-18",
    "ExchangeName":"binance",
    "transactionType":1,
    "cryptoAssetId":5
}

###
GET {{url}}/list-assets?currencyName=usd
# &cryptoCurrency=btc&sortColumn=link&page=1&pageSize=3&sortOrder=asc


###
GET {{url}}/id/5