@url = http://localhost:7071/api/Function1

POST {{url}}
Content-Type: application/json

{
  "Customer": {
    "Name": "John Doe",
    "Email": "john@example.com",
    "Phone": "123-456-7890"
  },
  "Address": {
    "Street": "123 Main St",
    "Number": "Apt 4B",
    "City": "Cityville",
    "State": "ST",
    "ZipCode": "12345"
  },
  "Product": {
    "Name": "Widget",
    "Quantity": 2
  },
  "WarrantyType": 1,
  "ServiceType": 1,
  "WarrantyQtd": 2,
  "ExcecutionTime": 5,
  "PaymentMethods": "Credit Card",
  "TotalPriceProducts": 100,
  "LabourValue": 50,
  "TotalPrice": 150,
  "Power": "220V",
  "Notes": "Additional notes go here"
}
