@url = http://localhost:7071/api/proposals

POST {{url}}/create
Content-Type: application/json

{
  "Customer": {
    "Name": "Douglas",
    "Email": "douglas@example.com",
    "Phone": "11941012994"
  },
  "Address": {
    "Street": "123 Main St",
    "Number": "Apt 4B",
    "City": "Cityville",
    "State": "ST",
    "ZipCode": "13218110"
  },
  "Products": [
    {
      "Name": "Widget",
      "Quantity": 2
    },
    {
      "Name": "Caco",
      "Quantity": 2
    }
  ],
  "WarrantyType": 1,
  "ServiceType": 1,
  "WarrantyQtd": 2,
  "ExcecutionTime": 5,
  "PaymentMethods": "Credit Card",
  "TotalPriceProducts": 100,
  "LabourValue": 60,
  "TotalPrice": 150,
  "Power": "220V",
  "Notes": "Additional notes go here"
}

###
GET {{url}}/1
Content-Type: application/json

{
  "proposalId":1
}