name: Run End-to-End Tests

on:
  pull_request:

env:
  NODE_VERSION: "20"

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install
        working-directory: ./web-app

      - name: Build the application
        run: npm run build
        working-directory: ./web-app

      - name: Start the application
        run: npm start &
        working-directory: ./web-app
        env:
          CI: true

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:4200
        working-directory: ./web-app

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
          record: true
          env: CYPRESS_RECORD_KEY=${{ secrets.CYPRESS_RECORD_KEY }}
        env:
          CI: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
